services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=creditas-loan-simulator'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=creditas'
    ports:
      - '5432'
