version: '3.8'

services:
  k6:
    image: grafana/k6:latest
    container_name: k6_performance_test
    volumes:
      - .:/app
    command: run /app/scriptTestePerformance.js
    network_mode: host
