CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS PERSON (
    ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    DOCUMENT VARCHAR(11) UNIQUE NOT NULL,
    BIRTHDAY DATE NOT NULL,
    EMAIL VARCHAR(70),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS LOAN_SIMULATION (
    ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    PERSON_ID UUID REFERENCES PERSON(ID),
    CURRENCY VARCHAR(3) NOT NULL,
    LOAN_AMOUNT NUMERIC(10,2) NOT NULL,
    LOAN_AMOUNT_BRL NUMERIC(10,2) NOT NULL,
    QT_INSTALLMENTS INTEGER NOT NULL,
    TOTAL_AMOUNT_TO_PAY NUMERIC(10,2) NOT NULL,
    INSTALLMENT_AMOUNT NUMERIC(10,2) NOT NULL,
    TOTAL_INTEREST NUMERIC(10,2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100)
);